name: stackup
version: "0.1.0+git"
summary: A simple CLI application for managing your Linux Server.
description: |
  Managing your own Linux server has never been easier. Install the server
  stack and configure your instance in the cloud of Google Cloud Platform,
  Amazon Web Services, DigitalOcean or any of your preference.

confinement: devmode # use 'strict' once you have the right plugs and slots
grade: devel # must be 'stable' to release into candidate/stable channels
type: app

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  stackup:
    plugin: go
    go-importpath: github.com/riipandi/stackup
    source: .
    source-type: git

apps:
  stackup:
    command: bin/stackup
    plugs: [home, network]
